from Modeler import *

app = MyApp("ip placeholder","port placeholder")

app.connect()
app.command()
app.wait(3)
app.takeoff()
app.printX()
app.printY()
app.cw(45)
#app.ccw(405)
app.forward(250)
app.printHeading()
app.printX()
app.printY()
app.printHeading()
app.wait(2)
app.up(50)
app.wait(2)
app.down(50)
app.wait(2)
app.land()
app.disconnect()
app.startTest()
app.run()